### ISSUE TITLE
Getting Error for Omitted Cost Pool and  Tower Tags

### ISSUE THREAD

**Issue by TsitsiL** [ombegov/ITDB-schema#110]
Name: Sriram Avasarala
Organization: Treasury
Urgency: Medium
Description of Issue: 
We are getting the error below when we try to submit Type 04 investment with the costpool and tower tags completely omitted.

Alert Error 1871: Element '{urn:us:gov:update-ITBudget-ext}FunctionalBusinessSponsorInformation': This element is not expected. Expected is ( {urn:us:gov:update-ITBudget-ext}CostPools ).

Note: this issue was pulled from #93

**Comment by TsitsiL** [comment]
Created a ticket in JIRA for this issue for team to look at.

**Comment by TsitsiL** [comment]
Please retry with the 2 required tags, just with amounts all set to 0.

Currently the CostPools and ITTowers elements are both required by schema because of the Total Internal Labor Cost Pool and the Total IT Security and Compliance Cost Tower that are required for most investments. 


Example of what you should retry:

      </DME>
      <CostPools>
        <CostPool>
          <CostPoolCategory>Total External Labor Cost</CostPoolCategory>
          <PriorYearAmount>0</PriorYearAmount>
          <CurrentYearAmount>0</CurrentYearAmount>
          <BudgetYearAmount>0</BudgetYearAmount>
        </CostPool>
      </CostPools>
      <ITTowers>
        <ITTower>
          <ITTowerCategory>Total IT Management Cost</ITTowerCategory>
          <PriorYearAmount>0</PriorYearAmount>
          <CurrentYearAmount>0</CurrentYearAmount>
          <BudgetYearAmount>0</BudgetYearAmount>
        </ITTower>
      </ITTowers>
      <FunctionalBusinessSponsorInformation>

This was tested this in development, and it worked. Let me know if it doesn’t.

**Comment by SriramAvasarala** [comment]
The xml is validated successfully with the two tags with zero values. Thanks You.

**Comment by GihaVillazon** [comment]
Great! will close this ticket. 

Thank You.

**Comment by SriramAvasarala** [comment]
HI Giha/Tsitsi, I have few questions about Total IT Security and Compliance Cost Tower in IT Portfolio. Please confirm. If you are planning to change any of these validations in the upcoming build please let us know.

1. Is it required for every investment (Part 1/Part2/Part3) or is it required only for Part 3 Type 02 - IT Security and Compliance investment? 
2. If it is not required for Part 1 and Part 2 , should we omit the node (or) should we send the tower node as below. 
<ITTowers>
    <ITTower>
      <ITTowerCategory>Total IT Management Cost</ITTowerCategory>
      <PriorYearAmount>0</PriorYearAmount>
      <CurrentYearAmount>0</CurrentYearAmount>
      <BudgetYearAmount>0</BudgetYearAmount>
    </ITTower>
  </ITTowers>

**Comment by rydougherty** [comment]
Hi Giha and Tsitsi, I have a follow up question for the initial issue posted by Siram. For Type 4 investments, there should be no validations on whether or not the Internal Labor or Security provide cost nodes. On pages 23 and 27 of the guidance it clearly lays out that Type 4 investments are not required to break out Cost Pool and IT Tower expenses (including Internal Labor and Security). Agencies should therefore, be able to drop all cost nodes instead of submitting $0.

> Columns 29-55 include the IT Cost Pools from the TBM Taxonomy. Definitions are provided in Appendix E. The only cost pool data that is required in the FY 2019 submission year is Total Internal Labor, as that data is related to the FTE costs that have been captured in the CPIC budget submissions for many years. While the TBM definition of Internal Labor includes more than just Government FTE costs, Agencies can simply include these Government FTE costs. Reporting all applicable IT Cost Pools is encouraged for Agencies that can, and OMB acknowledges that Investments will not likely have costs associated with all IT Cost Pools. Funding Transfer Investments (Investment Type “04”) are not required to break down costs in this manner.

Furthermore, the suggested solution of always submitting $0 for Security and Internal Labor jeopardizes data quality. Because the Cost Pool/IT Tower breakdown is optional for Type 4 investments, Agencies will still have ability to submit such breakdowns, or nothing at all. These two avenues Agencies may proceed down for Type 4 investments will cause issues as $0 and blank are inherently different values.

To illustrate this issue, we will have Agencies who wish to submit IT Towers for Type 4 investments and may report their funding going to Application, with $0 in Security. Other Type 4 investments may contribute to Security programs, but will omit all IT Towers since the Towers are optional. However, if the Agency in the latter example provides $0 Security expenses to bypass the validation error, they would be inaccurately representing their spending breakdown.

**Comment by TsitsiL** [comment]
Good afternoon Ryan,

The suggested solution for submitting zeros is a workaround until the issue is resolved. We still intend to implement the expected behavior of allowing agencies to omit these tags entirely and we have a ticket in place for it slated for deployment in Release 09B.
I will go ahead and close this ticket as the fix for it is in ITD-821 with development in progress. If there are still issues after the deployment, we can reopen the issue.

**Sriram** - please create a separate GitHub issue for your new issue. Including new issues within old issues does carry the risk of them not being addressed. We need  it separated so it can be triaged and handled as a separate issue.

**Comment by SriramAvasarala** [comment]
Thanks Tsitsi. **OMB didn't communicate that submitting zeros is a work around until the issues is resolved, when I reported it initially.** The responses to tickets are very confusing. I will open a new ticket as you suggested.

**Comment by TsitsiL** [comment]
Thanks Sriram, my apologies for not making that clear that it was a temporary fix/workaround to bypass the error. I had noted it on our end and kept the ticket alive with the understanding that what we gave you was a workaround.
Thanks!

**Comment by TsitsiL** [comment]
Just confirmed that the fix for this issue has been included in 08B Hotfix 1 and will be deployed on Monday August 28. For Type 4 Investments, the cost pool and IT Towers will be made optional so agencies will be able to omit them entirely.
