### ISSUE TITLE
Server Error Upon SIR Update Submission

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#111]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: When submitting an overall SIR update, an Internal Server Error is returned by the IT Dashboard. This issue appears to be isolated to sending update operations, as I did not receive the error when submitting the add operation.

I will email over files soon.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We are looking into this, will keep you posted. 

Thank You.

**Comment by rydougherty** [comment]
Hi Giha- doesnt look like this is resolved in last nights release. The issue appears to boil down to IT Dashboard expecting us to submit the agencyID fields for contracts and metrics. However, Agencies should either be able to use the OMB IDs (contractID/metricID etc) or the agencyIDs, but no both.

During the add operation both OMB ID and agencyID should be optional, and during the update operation one of OMB ID or agencyID should be required.

**Comment by rydougherty** [comment]
We are also seeing this with the agencyCapabilitID and the update operation for the Costs and Capabilities table.

**Comment by GihaVillazon** [comment]
Hi Ryan,

We have added the issue to be fixed with the 08B Hotfix release. 

Thank You.

**Comment by rydougherty** [comment]
Following up again, we are seeing this within the add operation as well for the agencyContractID and the agencyCapabilityID

**Comment by GihaVillazon** [comment]
Ryan we will have the fix in 08B Hotfix. 

Thank You.

**Comment by rydougherty** [comment]
Hi Giha- we are still running into this issue for End User Investments. I will email over files soon.

**Comment by ojedanico** [comment]
We ran into issues with code for this and pushed our hotfix out before we were able to correct the issues below.  And will be fixed in 8b2 Hotfix 2 to be deployed COB 8/30. 

Failures expected:
1. If operation = add and record ID is provided, display error
**This is Fixed no work required - Error is in place**

2. If operation = add and no record ID is provided but an agency ID is provided, verify agency ID is not already in use for a different record for this SIR and display error if already in use.
**Bug. No error is being shown when it should be. Got success, but expected failure.**

3. If operation = update and no record ID or agency ID is provided, display error
**Bug. "Undefined index: agencyCapabilityID" is shown but some more appropriate message should be shown.**

4. If operation = update and record ID is provided, verify record ID belongs to a record for this SIR and display error if it doesn't
**Bug. "Undefined index: agencyCapabilityID" is shown but some more appropriate message should be shown.**

5. If operation = update and no record ID is provided but an agency ID is provided, verify that agency ID corresponds to a record for this SIR and display error if it doesn't (need to add the record)
**Bug. "Undefined index: agencyCapabilityID" is shown but some more appropriate message should be shown.**

6. If operation = update and both record ID and agency ID are provided, verify that agency ID is not already in use for a different record related to this SIR and display error if agency ID already in use
Expect Success:

**Bug. "Undefined index: agencyCapabilityID" is shown but some more appropriate message should be shown.**

7. If operation = update and no record ID is provided but an agency ID is provided, verify that agency ID corresponds to a record for this SIR and update record with that agency ID
**Bug. Issue #1 reported by Samira. Should be allowed to update with the record ID only.**

**Comment by rydougherty** [comment]
Hi Nico- the above scenarios cover the Contracts issue i listed out. I am receiving another Server Error for the Security Investment when I clear out all the errors and warnings. I am creating new issue for this

**Comment by rydougherty** [comment]
One question about your response in point 4:

>If operation = update and record ID is provided, verify record ID belongs to a record for this SIR and display error if it doesn't
Bug. "Undefined index: agencyCapabilityID" is shown but some more appropriate message should be shown 
> 

Just to be clear, if you are providing a record ID that is valid, and no Agency ID, then there should be no error shown at all. This is not a case where a more "appropriate message" is needed. There should be no error or message at all.

**Comment by ojedanico** [comment]
Just to be clear, if you are providing a record ID that is valid, and no Agency ID, then there should be no error shown at all. This is not a case where a more "appropriate message" is needed. There should be no error or message at all.

**Yes, this will be fixed in hotfix 2 and will not show invalid error messages.**
