### ISSUE TITLE
Validation Confirmation

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#121]
Hi,

One of my customers received this message when validating its ITPS - "Type 5 investments with Infrastructure Management Category 5 must have exactly one Data Center ID".  Based on the guidance and validations you published, Category 5 (Data Center) investments must submit a data center ID, but there's nothing explicitly prohibiting the submission of multiple.  Basically, my customer just wants OMB's confirmation of the validity of the error.  

Thanks!
Courtney

**Comment by GihaVillazon** [comment]
Hi Courtney, 

That is correct, "Type 5 investments with Infrastructure Management Category 5 must have exactly one Data Center ID". 

"The Data Center ID(s) should be populated wherever there is a correlation of associated funding with the investments. The Data Center Standard Investments – Standard IT Infrastructure and Management Category: 05, will definitely have Data Center IDs." Retrieved from Guidance page. 32 Column 89.

Thank You.

**Comment by courtneycorwin** [comment]
Right - I agree with the guidance.  The guidance doesn't indicate that Type 5/Category 5 investments will have only 1 data center.  In fact, it uses the plural "will definitely have data center IDs".

**Comment by GihaVillazon** [comment]
for Type 5 if there are multiple data center ids, they will have each investments tied to the data center id.

**Comment by courtneycorwin** [comment]
The guidance doesn't really specify that it's a one-to-one relationship.  I'm letting my customers know of the validation.

**Comment by rbrown94** [comment]
The final OMB guidance is very specific on pg. 33, column 89: "Data Center ID - The unique identifier (or list of the identifiers) from your agency's data center inventory...", "...Data Center ID(s) should be populated wherever there is a correlation of associated funding with the investments."

Furthermore, from the 7/21/17 training on the FY 2019 Guidance given by OMB, slide 15, it specifically states "Allow multiple IDs on any investment in portfolio".

It would seem that either OMB changed their mind since the guidance was released or the validation is incorrect.  Please confirm.
