### ISSUE TITLE
Security SIR Costs and Capabilities Validation

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#122]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: 
When attempting to validate an IT Security SIR through the annual, I am receiving the following errors:  **The sum of all IT security compliance capabilities for PY 0.001000 should exactly match Total Security and Compliance Cost PY 1 from the investment in the IT Portfolio.**

The investment currently has only one capability, with the same funding amounts as was submitted on the AITPS. I will send you both the AITPS (already submitted) file and SIR request and response file that I am seeing. Can you provide some insight onto how to clear this?

**Comment by GihaVillazon** [comment]
Hi Alex, 

The 09A deployment will address this issue.

Thank You.

**Comment by ojedanico** [comment]
Github issue 122 is fixed (Test with the included files which replicate the issue as presented on github/the files they sent) however, we could not squeeze it into 8b hotfix3. It is slated to deploy with 9a.

The origin of the issue was a small bug in the value calculation which assumed that there would always be multiple capabilities to loop through, causing it to loop through object fields if there was only one and generate erroneous data.

**Comment by GihaVillazon** [comment]
I will be closing this ticket, as the fix was deployed with 08B Hotfix2. 

Thank You.
