### ISSUE TITLE
Type 04 Required to submit 0 for Security Tower

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#131]
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: What is the genesis of this validation error? Error: Total PY IT Security Spending must be 0 when investment type is funding contribution.

This is not mentioned in the guidance. The only instruction is that all cost pools and towers are optional (nillable) for Type 04. It seems odd that it is required, but required to be 0. Why not allow it to be omitted? And why not allow them to provide a value if they know the cost? This has me a bit confused.

**Comment by GihaVillazon** [comment]
Hi Alex, 

 
We will have the fix for this simply by making the CostPools and ITTowers elements optional in schema, therefore you can leave them off completely for type 04 investments. This change will be included in the 08B Hotfix deployment. 

Thank You.

**Comment by murrayalex** [comment]
That is great news, Giha. Thanks for the quick response.

**Comment by SriramAvasarala** [comment]
Giha,

"We will have the fix for this simply by making the CostPools and ITTowers elements optional in schema, therefore you can leave them off completely for type 04 investments" 
This means we can omit the tags from the xml submission. You have mentioned earlier on the other ticket (110) that we cannot omit the tag and we should submit Total Internal Labor and security tower with 0 values. This is very confusing. Can OMB clarify on when we should omit the cost pool and tower tags for what type of investments and when do we submit tags with values. 

Thanks,
Sriram

**Comment by TsitsiL** [comment]
Hi Sriram,
While our developer was resolving this issue, he found that it also applies to #110 so the fix will address both. For #110, you will be able to omit the tags entirely when the fix is deployed. The submission of the tags with zero values was a workaround until we completed the fix which is part of of the hotfix to be deployed on monday August 28.

**Comment by murrayalex** [comment]
Hey Giha,
I have a follow-up question on this. I am receiving this error even when submitting "0" for type 04 investments. Is this error being removed completely, or are you only making the nodes optional. It seems that they do not actually accept 0 either, which makes it problematic for Agencies that want to submit data for these investments.

I'm not sure making those nodes optional will address all of the issues here.
