### ISSUE TITLE
SIR Error Inconsistent Responses 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#138]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Get Investment Operation directed at the SIR API does not return errors wrapped underneath `<ErrorsAndWarnings>` tags. In addition we are receiving an error for including the Data Center ID node (that is likely a mistake, but we can discuss in another Issue) wrapped under `<SchemaValidationError>` nodes. This is the opposite of our expected behavior based upon the sample Response file provided last week. We expect all errors generated from the SIR API to consistently return underneath `<ErrorsAndWarnings>` tags.

Get Response Error:
```
<InvestmentReportResponse>
	<towers>
		<tower>
			<operation>get</operation>
			<towerDetails>
				<UII>011-000100026</UII>
			</towerDetails>
		</tower>
	</towers>
	<response>
		<tower1>Error: Investment Report not found for UII 011-000100026.</tower1>
	</response>
</InvestmentReportResponse>
```

Data Center Error ID:
```
 <schemaValidationError>
    <errors>
      <error>Error 1871: Element 'dataCenterID': This element is not expected. on line 1</error>
    </errors>
  </schemaValidationError>

```
Example Response Error:
```
       <ErrorsAndWarnings>
          <errors>
            <error>An Investment Report with UII 000-999990220 already exists. You may not use an add operation for this UII.</error>
          </errors>
          <warnings>
            <warning>POC is unexpected for report type 06 and will not be saved.</warning>
          </warnings>
        </ErrorsAndWarnings>
```

**Comment by austin-moffa** [comment]
There are 3 special cases with errors to watch for. They are: 
'schemaValidationError', 'CriticalErrors', and 'LogicalStructureErrors'.

Schema validation is the first step. If schema validation errors are returned, there will be no other errors in the response.

Next is Critical Errors, which again - like schema validation - mean no other errors will be returned.

Logical structure validation errors actually are warnings that occur when a section is included in a report that does not apply to that report. In that case, the section is omitted and warning is presented. This section can be returned along with the general errors array.

1. Schema validation error example:
 <response>
    <tower1>
      <status>Submission Failed</status>
      <schemaValidationError>
        <errors>
          <error>
Error 1871: Element 'example': This element is not expected. on line 13
</error>
        </errors>
      </schemaValidationError>
    </tower1>
  </response>

2. Missing UII/Critical Errors Example:
<response>
    <tower1>
      <CriticalErrors>
        <errors>
          <error>The submitting user must match the UII agency code.</error>
        </errors>
      </CriticalErrors>
      <status>Submission Failed</status>
    </tower1>
  </response>
  
3. Logical Structure Errors:

 <response>
    <tower1>
      <LogicalStructureErrors>
        <warnings>
          <warning>costsAndCapabilities section is unexpected for report type 06 and will not be saved.</warning>
        </warnings>
      </LogicalStructureErrors>
      <towerDetails/>
     <investmentCostDetails>
        <investmentCostDetail>
          <errors>
            <error>This is an example error</error>
          </errors>
		  <warnings>
		  	<warning>This is an exmaple warning</warning>
		</warnings>
        </investmentCostDetail>
      </investmentCostDetails>
      <status>Submission Successful</status>
    </tower1>
  </response>
  
  
4. General/Field Level Errors (They will be nested inside the element):
 <response>
    <tower1>
      <towerDetails/>
      <investmentCostDetails>
        <investmentCostDetail>
          <errors>
            <error>This is an example error</error>
          </errors>
		  <warnings>
		  	<warning>This is an exmaple warning</warning>
		</warnings>
        </investmentCostDetail>
      </investmentCostDetails>
      <status>Submission Failed</status>
    </tower1>
  </response>
  
 5. Get Errors: (Get errors are treated the same as critical errors, since it's a failure to match on a UII)
  <response>
    <tower1>
      <status>Get Failed</status>
      <CriticalErrors>
        <errors>
          <error>Error: Investment Report not found for UII 018-000234008.</error>
        </errors>
      </CriticalErrors>
    </tower1>
  </response>

Let me know if this doesn't clear things up and I can provide some more examples/documentation.

**Comment by ojedanico** [comment]
Jira ticket 882 to be deployed with 9a release

**Comment by rydougherty** [comment]
Hi Austin- thanks for sending all of these over. We can live with having the different error types on our end.  However, all the examples you sent over are from the "bottom half" (below the `<response>` node) of the response file. Can you please confirm that all these errors will show in both the top half and bottom half of the response file?

**Comment by austin-moffa** [comment]
All errors that are associated with a field will show up in that respective section's "ErrorsAndWarnings" element, however the meta-level ones (schema, structural, missing uii/invalid agency sorts of things) only appear in the response section.

**Comment by rydougherty** [comment]
Hi Austin- that will be problematic. When you submit multiple towers, there is no way to link the responses in the "bottom half" to the an individual investments data. If an individual investment is submitting an extra node, there is no way to determine which investment is associated with that Schema Validation Error.

**Comment by austin-moffa** [comment]
A schema level validation will not parse any of the file, therefore it is associated with a line number rather than a given tower (because it cannot parse the towers.) It also doesn't return the original contents of the file because the contents could not be parsed.

Critical validation failures will always return an id which the system failed to match (UII) or an agency mismatch warning.

The structural errors I'll grant could be hard to associate back, however all of the errors in the response are nested within numbered "tower" tags that correspond to the investments position in the submission file. If that is not sufficient, we can consider adding these special errors into the tower element of the original submission. Our system is designed to parse the bottom half and the top errors are for human readability, so if you are parsing the top and find that there could be more useful information returned, just let us know (and preferably the formatting you would prefer).

**Comment by rydougherty** [comment]
Even if you cannot parse the data sent across, can you still place the error in the top half of the file? 

If not, we would request to replace the tower1, tower2, tower3 etc nodes in the bottom half with simply tower. The itemized nodes cause issues since there is not a contistent handle for us to search for when parsing the file. If you take this approach we would also like to see some
Indication through a status node that the submission has failed in the top half.

**Comment by TsitsiL** [comment]
ITD-867 deployed on 9/6/17. Closing this issue.
