### ISSUE TITLE
Projected Dates and Costs for Agile Activities - High Priority

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#187]
Hi guys,

I just heard from one of my users that you made the decision to add these data elements back to the agile activities table with the next hotfix.

1. When is that hotfix going to be implemented?

2. Most of my agencies have completed submission.  Do they have to resubmit any investments with agile activities before Monday night or can this be reconciled during a monthly?  What instruction and guidance are you giving out to the agencies?

Thanks!
Courtney

**Comment by TsitsiL** [comment]
Hi Courtney,

the hotfix includes a schema update to allow the projected values to be submitted for agile activities and we expected it to go through tonight or tomorrow latest. The preference is to have the info resubmitted for agile activities before monday night, but you can make these updates during the monthly (starting in October). 
We will ask Justin and Kelly about sending official instruction and guidance on this to agencies.

Either way, I will update this comment when we have deployed the fix.

Thanks!

**Comment by courtneycorwin** [comment]
Thanks, TsiTsi!

I get that they're optional, but if they're not submitted then the variance calculations are going to be very inaccurate.  It's easy enough to change our process to allow these categories to be submitted to IT Dashboard, but there's not a lot of time for users to go back in, enter the data, and revalidate/submit everything.

Giving agencies the option to update these in the October monthly without penalty would be very appreciated.  Thanks!!

**Comment by TsitsiL** [comment]
Understood Courtney, we will consult with Justin and Kelly to get their direction on this.

Thanks!

**Comment by murrayalex** [comment]
Is this a change to the BY19 Guidance? This is the first we are hearing of this, but agree that it could have impacts for our Agencies. The sooner we can get clarification on this the better.

**Comment by TsitsiL** [comment]
Good morning Alex,
A little background on this issue: in the BY19 guidance, Table B.2.2. that can be leveraged to enter information about agile activities does not include the projected values. Our schema was implemented to follow the guidance. When an agency reached out to us this week about the impact of not having these fields on the variance calculations, we did consult with OMB yesterday on how to proceed. For the immediate fix, the schema was updated to allow projected values for agile activities. This fix, as I mentioned to Courtney, is in the hotfix to be deployed today. All of this happened in a relatively short time and OMB will communicate instructions on this as soon as possible. 

Thanks!

**Comment by murrayalex** [comment]
If this field is being added back in as part of the variance calculations, then this is a major change that will be a problem for our Agencies given the end of this window. We brought this issue up (#128) over three weeks ago, and it was communicated that variance calculations would not be impacted. We are concerned about the impact this will have on our Agencies submissions, and therefore  we are opposed to adding this back in at the eleventh hour without further discussion.

**Comment by TsitsiL** [comment]
In #128, the scenario that was not considered is for in-progress agile activities that do not have the actual values (because they are not completed) AND do not have projected values (because these were no longer being collected). Having both of these values not provided affects the variance calculations. We presented this scenario to Justin yesterday during the vendor call and after some discussion the decision was made shortly after to allow projected values to be provided for agile activities as optional fields.
I am personally prioritizing getting OMB to communicate their decision, expectations, and next steps  ASAP.

Thanks

**Comment by TsitsiL** [comment]
Follow up on this - I did get confirmation from Justin that following this hotfix, we do **not** require the projected values to be included in the annual submissions, so you will not have to resubmit any business cases for the sole purpose of including projected values. You can include the projected values in the monthly submissions starting in October. If you do have the capacity to resubmit the annual submission with the projected values, that is great, but we are not setting that expectation as these fields have been added back as optional fields and there will be no validation errors should you choose not include them.

There will be communication from OMB regarding expectations in the long term, but for now, you have the option of continuing your annual submissions with or without the projected values for agile activities; or include them in the monthly submissions.

The hotfix was deployed this morning so you should have the option above now. I will go ahead and close this issue since the hotfix was deployed.

Of course please reach out to us if you have any questions.

Thanks!

**Comment by murrayalex** [comment]
Hey Tsitsi,

Thanks for the clarification. I have a few follow-up questions:

1. For Agile Activities that existed in BY18, will their existing Projected data now be carried over into BY19 and used to calculate the variance score? We strongly discourage this, as our Agencies have not and will not be able to provide updated Projected values during this submission window, which could lead to incorrect variance data.
2. For Agile Activities that were submitted for the first time this week and have no Projected or Actual data, how will their variance scores be calculated and factored into the overall project score? Will they just be ignored? 

Appreciate your assistance on this. We want to be able to effectively communicate the impact of this change to our Agencies.

**Comment by TsitsiL** [comment]
Hi Alex, I completely understand your concerns. my responses are below:

1. The existing projected data from BY18, if it existed before June 1, 2017, will be in the BY19 data. You do have the option to update it now with a resubmit if you have the capacity to do so, but this is not OMB's expectation - you can reconcile differences in the monthly starting in October. I mention the June 1 date because, as you may already know, the data in our BY19 database at the beginning of submissions is from before then and there is a fix being worked for that, during which agencies are still to continue submitting their BY19 data as it will be saved correctly. OMB is aware that some of the variance calculations will not be accurate given the missing and/or old data and will communicate the long term solution for this. In the meantime, you have the option to provide the projected values now so the calculations are accurate for the annual submission; or do so in the monthly. OMB is not expecting these corrections in this annual submission.

2. Variance caluculations return null values if both the projected and actual values are not provided. This mean that they will not be factored into the overall project score (which only considers non-null values).

Again, OMB is completely aware and accepts that variance calculations for some agile activities will not be accurate for the annual submissions. The expectation is that additions of and updates to projected values will be made via the monthly operations for now. Again note, the projected values are optional so you will not get any validation errors if you leave them out in the annual or the monthly submissions. This is the direction for now.

OMB will communicate the long term solution officially to agencies.

Thanks!

**Comment by courtneycorwin** [comment]
Hi TsiTsi,

I've pretty much resolved this with my agencies - I think that only one or two are going to resubmit their investments and the rest will just wait to reconcile with the October update.  

Given that the variance calculation is the main issue regarding these data elements, is it possible to hide the variance calculations until after the October submission or make a note that they are not considered accurate until after the October submission?

**Comment by TsitsiL** [comment]
Thanks Courtney,

to be clear, most of the BY19 pre-decisional investment data is NOT publicly available, this includes variance calculations. You will be able to see this data just for your agency as a logged in user, but all other agencies and the public will not be able to. OMB users are the only ones able to see all of the agencies' data.  It is only after the pass back submissions do we allow post-decisional data to the public. Even then, it is masked accordingly as deemed by each agency.

OMB will send out the long term solution and relevant communications about this issue.

**Comment by rydougherty** [comment]
Is OMB planning on sending out communications to Agencies regarding the rationale behind the reinstatement of the Agile Projected values?
