### ISSUE TITLE
IT Dashboard Offline?

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#192]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: Did OMB turn off Monthly Submissions to the IT Dashboard? One of our Agencies is attempting to run a validation and is receiving the following error:

> The operation updatePerformanceMetric is not available at this time

**Comment by GihaVillazon** [comment]
Hi Ryan, 

The submission window is closed now, the error is expected.
The monthly submission will open up early October, the date is to be determined. 

Thank You.

**Comment by rydougherty** [comment]
Hi Giha, thanks for the response, and it makes sense given the data reconciliation process on your plate. But, is OMB planning on communicating that the Dashboard is closed out to Agencies. I know you suggested that Agencies avoid submissions until October, however, that is different than closing down the Dashboard all together.

**Comment by TsitsiL** [comment]
Good afternoon Ryan,

We have closed all of the submission windows as Giha mentioned, but this does not mean that the dashboard is closed down.  We still continue to provide feeds for IT Budget data while we are working on the business case feeds. Also, there are other parts of the dashboard not reliant on investment data at all on the site e.g Cost Savings, DCOI Closures, DCOI Optimization etc). Not accepting submissions for the rest of September does not mean that the dashboard is closed. 

The communication that Kelly sent out on 9/13 on monthly submissions is below:
4)	Can agencies perform monthly submissions in September? 
Answer: We ask that agencies hold off on any monthly submissions in September.  If there are extenuating circumstances where updates are necessary, please reach out and we will take requests on a case by case basis.  This is to help reconcile data so that we have a clean starting point before monthly submissions recommence in October. 

Thanks!

**Comment by rydougherty** [comment]
Hi Tisitsi- thanks i see Kelly's email from 10 minutes ago articulates how Agencies should move forward if they have questions regarding submitting data now.

**Comment by TsitsiL** [comment]
Wonderful! I will go ahead and close this issue. and of course reach out to us with any concerns!
