### ISSUE TITLE
getInformation request via UI have empty response file

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#193]
Name: Barry Pannell
•Organization: DHS/MBC
•Urgency: High
•Description of Issue: Submitted 2 different getInformation request XML files via the UI this morning (wed 9/20).  The first was a combination of getContracts and getAcquisitions for 39 investments. The second submission file was getInvestment requests for 39 investments. Both submissions returned they were successful/no errors.  The response files only had the original request with no investment information.  

Want to use this information to verify the deactivations of contracts and acquisitions.  The data feeds for contracts and acquisitions are not operational so am dependent on getInformation to see details.

**Comment by GihaVillazon** [comment]
Hi Barry, 


The problem seems to be that submission was with validateOnlyIndicator = "true".  If you remove that (or sets it to "false") you should see the investment data with the getInvestment operation.  (getContract will still only show contract information and no investment data, but you can submit the getInvestment with the getContract.)

Hope it helps please let us know if further clarification is needed. 

Thank You.

**Comment by barrypannell** [comment]
Yes.  That solved my issue.  Thanks.

**Comment by GihaVillazon** [comment]
Great I will close the ticket now. 

Thank You.
