### ISSUE TITLE
ITDB error for UII

### ISSUE THREAD

**Issue by JoeGom** [ombegov/ITDB-schema#222]
While submitting the MITBC for UII 005-000003240, I received errors stating that;

1.The UII is already in use and,

2. The UII is deactivated and cannot be used for this investment.

This investment and the UII was initially submitted last September with the BY19 annual submission and did not trigger any errors like the ones above. Moreover, when the ITPS was submitted this past Tuesday, we did not receive any errors like the ones above for this UII. Can you please let me know when - and if - this UII was deactivated and if the UII was not deactivated, how do I complete the submission for this MITBC and get past this error.

Thank you.

Joe Gomes
USDA OCIO Capital Planning and IT Governance

**Comment by TsitsiL** [comment]
Note - Joe sent this issue to the help desk and we created ITD-1363 for it which was escalated and prioritized to be deployed today. later reported issue #223 appears to be related to this one. We think the fix for ITD-1363 will resolve both issues. I will loop back when we complete the fix so Joe can check both issues.

Thanks!

**Comment by TsitsiL** [comment]
Hi Joe,

we just deployed the fix. Please retry your submission and let us know if you have any issues. I will close this issue here so you reach out to the help desk if we need to re-open the ticket.

Thanks!

**Comment by TsitsiL** [comment]
USDA retried submission using the updateInvestment instead of the addInvestment. Confirmed that submissions was successful.
