### ISSUE TITLE
Downloads from data feeds have duplicated data

### ISSUE THREAD

**Issue by JoeGom** [ombegov/ITDB-schema#223]
I just downloaded the ITPS from the Data feeds and for some reason, most of the rows - if not all - appear to be duplicated resulting in erroneous totals. The fiscal totals in columns U, V and W are just less than what a true double counting would result in. So not all rows are being exported as duplicates from the ITDB. I found this same issue yesterday when I downloaded the Budget Account Summary data and thought it was just a "one-off" but apparently the issue is more widespread.

Joe Gomes
USDA OCIO Capital Planning and IT Governance

**Comment by TsitsiL** [comment]
Good afternoon Joe,
this issue is related to #222 that you reported. we did find the underlying issue was duplicated data and as I wrote to you over the help desk email, we are working on a resolution today in ticket ITD-1363. The fix there should correct the feeds as well.

I will keep you posted with updates as I get them.

Thanks!

**Comment by TsitsiL** [comment]
Hi Joe,

we deployed the fix for #222 so I think it will resolve the duplicate data you are seeing in the feeds. Please recheck and let us know if not.

Thanks!

**Comment by TsitsiL** [comment]
from Joe:
I think we are good now with the fix deployed yesterday afternoon. I just checked the ITPS and Budget Account Summary downloads and they no longer include duplicate rows.

Issue resolved.
