### ISSUE TITLE
Non-standard infrastructure performance metric reporting in ITD user interface

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#239]
Issue: When viewing in ITD a DHS non-standard infrastructure investment (that was a major investment previously and reported performance metrics) the investment page shows the metrics from last year.  The investment did not report a business case this year because it was a non-standard infrastructure investment that was not required to report this year as a business case.  The metrics do not show a FY18 target because they would have only been of the business case update in September.  Actual results are not being reported as well.  Is OMB going to continue to present the metrics for this type of non-standard investment?  Does the department need to do something to remove the metrics?  
Submitter: Barry Pannell DHS INVEST Support/MBC

**Comment by gperatcg** [comment]
Per ticket 1474 and 1494 in JIRA, this issue is currently being resolved to ensure that business case data related to any investment that is not Type 01: Major is not displayed or included in current tables attached to the investment. This solution should resolve the issue on the Dashboard and is scheduled to be deployed on April 12 with the next sprint.

**Comment by TsitsiL** [comment]
Closing this ticket as it will be addressed on April 12.
