### ISSUE TITLE
Input Controls

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#41]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Input Controls (Character Count Restrictions) are still undefined for several of the new fields associated with the Standard Investment Reports. The three Acquisition Strategy fields within the Future Contracts Tables, and the two Brief Description fields located in Projects Tables are defined as only "Text" fields.

**Comment by ojedanico** [comment]
Hey Ryan, 

Yes, Keith pointed this out earlier to me... I have updated the data dictionary and we are currently in the process of uploading a new copy to address the issue 

For the Acquisition Strategy fields (Future Contracts tables) within the standard report as 1000 characters, due to the fact that 1000 characters is the field definition within major investments (Acquisition Strategy table).  
 
For the Brief Description fields (Standard Investment Projects tables) on the network and end user standard report, we have 2,500 characters due to the major investment definition currently set at 2,500 (B.1 Projects table).  

Again, this has been reflected in the data dictionary.
