### ISSUE TITLE
Optional Data within the AITPS

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#57]
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: How should Agencies submit data for optional Cost Pools and IT Towers they wish to omit from their submissions this September? 

I have noticed if you drop a CostPool or ITTower parent node (so no Category, PY, CY, and BY nodes) your submission successfully validates. So, presumably you could not report any External Labor or Application if desirable. However, you are unable to report BY values for an individual Cost Pool or IT Tower and omit PY or CY nodes. You are also unable to send blank values within the cost nodes(PY,CY, and BY). Is this by design or should you able to drop any cost node?

**Comment by ojedanico** [comment]
Ryan, 
You are correct the PY, CY, BY should be able to drop any cost node to reflect any scenario where an agency does not have a cost pool or IT tower cost or an agency decides to opt out this year. 

For example, an agency could have a Part 1, Type 1 investment with no Data Center cost which means PY, CY, BY would left blank. 

We were forward looking into the future which leaves a hole until TBM is fully implemented. 
Therefore, we will be updating the schema to address this issue during this sprint and should be in Aug 4th release.

**Comment by ojedanico** [comment]
Based on our conversation we will implement the suggestion of allowing null/blank vs 0 to indicate that there is no data for a given FY.

**Comment by courtneycorwin** [comment]
Does this mean that a sample update would look like this:

<CostPool>
<CostPoolCategory>Total Software Cost</CostPoolCategory>
<PriorYearAmount/>
<CurrentYearAmount/>
<BudgetYearAmount/>
</CostPool>

Or would the node be omitted altogether?

**Comment by ojedanico** [comment]
It turned out that it’s better to exclude amounts by omitting the node altogether, as opposed to submitting an empty or null value. The latter approach would have required much more substantial changes to the schema, which requires a numeric value for dollar amounts and doesn’t allow empties or nulls. The omission approach requires very minimal schema changes.

So for example, to submit Total Software Cost when you have amounts for all 3 FYs, you’d do this:

<CostPool>
<CostPoolCategory>Total Software Cost</CostPoolCategory>
<PriorYearAmount>100</PriorYearAmount>
<CurrentYearAmount>100</CurrentYearAmount>
<BudgetYearAmount>100</BudgetYearAmount>
</CostPool>

Or if you only have just a BY and a CY amount, you’d omit the PY node like this:

<CostPool>
<CostPoolCategory>Total Software Cost</CostPoolCategory>
<CurrentYearAmount>100</CurrentYearAmount>
<BudgetYearAmount>100</BudgetYearAmount>
</CostPool>

**Comment by courtneycorwin** [comment]
And if you have no costs for a cost pool?  Would you just omit Total Software Cost altogether?

**Comment by ojedanico** [comment]
Yes.

**Comment by rydougherty** [comment]
If you were to accidentally submit data  for a certain Cost Pool or IT Tower, there would be no way to blank out the value or remove it from the Dashboard. Is OMB fine with just overwriting values with zero in this scenario?

**Comment by ojedanico** [comment]
Throughout the FY 2019 cycle, Internal Labor is the only cost pool that will be required.  IT Security and Compliance IT Tower costs are mandatory for all applicable Investments for the September 2017 submission.  For the January 2018 submission, all applicable IT Tower costs (except for Application and Delivery) will be mandatory. While these fields are optional, the data will not be made public on the IT Dashboard.

**Comment by ojedanico** [comment]
Note that all records related to this submission, are recreated from scratch every time the submission is done, i.e. all existing data gets deleted and replaced with the new data.
