### ISSUE TITLE
export report for issues - filters on issues and responses 

### ISSUE THREAD

**Issue by ojedanico** [ombegov/ITDB-schema#88]
Build out a report of issues and comments for vendors to review - last 7 days or date from

**Comment by kimlercorey** [comment]
Yes, folks can look at issues that were created or updated in the last x days and the good news is one doesn't actually need an API request to do that - it can be done right in the guthub interface.

So, for example:  [https://github.com/ombegov/ITDB-schema/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20updated%3A%3E%3D2017-08-10%20](https://github.com/ombegov/ITDB-schema/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20updated%3A%3E%3D2017-08-10%20)

Will open all issues that are open that have been updated (e.g.comments and conversations are updates) on or after 2017-8-10.  

There are a ton of filters and specification one can use to build a query so it is simple to find or stay on top of relevant information here - https://help.github.com/articles/searching-issues-and-pull-requests/

BUT - I'll often actually just use a sort query (e.g. https://github.com/ombegov/ITDB-schema/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sort%3Aupdated-desc) because it can be bookmarked and will bring up all the issues sorted by lat activity. The last updated information is visible without going into the issue so I can just research as far down as needed to explore the time period I have in mind.

Anyrate, hope that is helpful and answers the question. If not- let me know!

Regards,
KC

**Comment by barrypannell** [comment]
The filter examples with the sorting is very helpful.  

Not sure if I saw "The last updated information is visible without going into the issue".     

That was the original thought.  Where I wanted to go was to get the issues exported to an alternate view ( 'WORD/EXCEL' like format) to see multiple issues 'opened'.  That way I could quickly read through the issues and the updates.  I did not want to read one at a time.  I wanted to read for updates and to see if it applied to my experience and see the responses/resolution more quickly.

**Comment by ojedanico** [comment]
In short, Yes you can use the GITHUB JSON API to pull data into excel or Google sheets but it needs a little code (like pullJSON below) and you need to decide your own view.


Regarding opening this view in another program lie excel - maybe the web api could help… e.g. 

https://api.github.com/repos/ombegov/ITDB-schema/issues?page=1&per_page=1000

Produces JSON output of all the issues in the query…

SEE JSON BELOW …..

Which maybe in itself could be considered a view and it has all the issues with all the fields. BUT, if for example, one chose to use function in google Sheets to sort the API data

From (https://gist.github.com/superstrong/bc60593321d46fa06774310b18ed41d0)

function pullJSON() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheets = ss.getSheets();
  var sheet = ss.getActiveSheet();

  var url="https://api.github.com/repos/ombegov/ITDB-schema/issues?page=1&per_page=1000";
  
   var response = UrlFetchApp.fetch(url); // get feed
  var dataAll = JSON.parse(response.getContentText()); //
  var dataSet = dataAll;
  
  var rows = [],
      data;
  
  for (i = 0; i < dataSet.length; i++) {
    data = dataSet[i];
    rows.push([data.url, data.state,data.body]); //your JSON entities here
  }

  dataRange = sheet.getRange(1, 1, rows.length, 3); // 3 Denotes total number of entites
  dataRange.setValues(rows);

}

Then they could just have the sheet with the specific data points they were looking for - this is an example with only URL, state and body ….

**Comment by danielwyork** [comment]
Note - https://api.github.com/repos/ombegov/ITDB-schema/issues?page=1&per_page=1000 will only give you open tickets. If you want to see ALL tickets, you need to run the following and concatenate the responses. I have not yet found a way to export all issues (Open and Closed) in one call:
https://api.github.com/repos/ombegov/ITDB-schema/issues?State=all&Page=1
https://api.github.com/repos/ombegov/ITDB-schema/issues?State=all&Page=2
https://api.github.com/repos/ombegov/ITDB-schema/issues?State=all&Page=3
https://api.github.com/repos/ombegov/ITDB-schema/issues?State=all&Page=4
